// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteApiContactsById, getApiContacts, getApiContactsById, type Options, postApiContacts, putApiContactsById } from '../sdk.gen';
import type { DeleteApiContactsByIdData, GetApiContactsByIdData, GetApiContactsByIdResponse, GetApiContactsData, GetApiContactsResponse, PostApiContactsData, PostApiContactsResponse, PutApiContactsByIdData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiContactsQueryKey = (options?: Options<GetApiContactsData>) => createQueryKey('getApiContacts', options);

export const getApiContactsOptions = (options?: Options<GetApiContactsData>) => queryOptions<GetApiContactsResponse, DefaultError, GetApiContactsResponse, ReturnType<typeof getApiContactsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiContacts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiContactsQueryKey(options)
});

export const postApiContactsMutation = (options?: Partial<Options<PostApiContactsData>>): UseMutationOptions<PostApiContactsResponse, DefaultError, Options<PostApiContactsData>> => {
    const mutationOptions: UseMutationOptions<PostApiContactsResponse, DefaultError, Options<PostApiContactsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiContacts({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiContactsByIdMutation = (options?: Partial<Options<DeleteApiContactsByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiContactsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiContactsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiContactsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiContactsByIdQueryKey = (options: Options<GetApiContactsByIdData>) => createQueryKey('getApiContactsById', options);

export const getApiContactsByIdOptions = (options: Options<GetApiContactsByIdData>) => queryOptions<GetApiContactsByIdResponse, DefaultError, GetApiContactsByIdResponse, ReturnType<typeof getApiContactsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiContactsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiContactsByIdQueryKey(options)
});

export const putApiContactsByIdMutation = (options?: Partial<Options<PutApiContactsByIdData>>): UseMutationOptions<unknown, DefaultError, Options<PutApiContactsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutApiContactsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiContactsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
