// This file is auto-generated by @hey-api/openapi-ts

export { deleteApiContactsById, getApiContacts, getApiContactsById, type Options, postApiContacts, putApiContactsById } from './sdk.gen';
export type { Address, ClientOptions, Contact, ContactWithFullName, DeleteApiContactsByIdData, DeleteApiContactsByIdResponses, GetApiContactsByIdData, GetApiContactsByIdResponse, GetApiContactsByIdResponses, GetApiContactsData, GetApiContactsResponse, GetApiContactsResponses, PhoneNumber, PostApiContactsData, PostApiContactsResponse, PostApiContactsResponses, PutApiContactsByIdData, PutApiContactsByIdResponses } from './types.gen';
