// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiContactsByIdData, DeleteApiContactsByIdResponses, GetApiContactsByIdData, GetApiContactsByIdResponses, GetApiContactsData, GetApiContactsResponses, PostApiContactsData, PostApiContactsResponses, PutApiContactsByIdData, PutApiContactsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiContacts = <ThrowOnError extends boolean = false>(options?: Options<GetApiContactsData, ThrowOnError>) => (options?.client ?? client).get<GetApiContactsResponses, unknown, ThrowOnError>({ url: '/api/Contacts', ...options });

export const postApiContacts = <ThrowOnError extends boolean = false>(options?: Options<PostApiContactsData, ThrowOnError>) => (options?.client ?? client).post<PostApiContactsResponses, unknown, ThrowOnError>({
    url: '/api/Contacts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiContactsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiContactsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiContactsByIdResponses, unknown, ThrowOnError>({ url: '/api/Contacts/{id}', ...options });

export const getApiContactsById = <ThrowOnError extends boolean = false>(options: Options<GetApiContactsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiContactsByIdResponses, unknown, ThrowOnError>({ url: '/api/Contacts/{id}', ...options });

export const putApiContactsById = <ThrowOnError extends boolean = false>(options: Options<PutApiContactsByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiContactsByIdResponses, unknown, ThrowOnError>({
    url: '/api/Contacts/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
