// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5077' | (string & {});
};

export type Address = {
    id?: number;
    line1: string | null;
    line2?: string | null;
    city: string | null;
    state: string | null;
    postalCode: string | null;
    country: string | null;
    contactId?: number;
};

export type Contact = {
    id?: number;
    firstName: string | null;
    lastName: string | null;
    email: string | null;
    dateOfBirth?: string | null;
    isFavorite?: boolean;
    primaryAddressId?: number;
    primaryPhoneNumberId?: number;
    addresses?: Array<Address> | null;
    phoneNumbers?: Array<PhoneNumber> | null;
};

export type ContactWithFullName = {
    id?: number;
    firstName: string | null;
    lastName: string | null;
    email: string | null;
    dateOfBirth?: string | null;
    isFavorite?: boolean;
    primaryAddressId?: number;
    primaryPhoneNumberId?: number;
    addresses?: Array<Address> | null;
    phoneNumbers?: Array<PhoneNumber> | null;
    fullName?: string | null;
};

export type PhoneNumber = {
    id?: number;
    number: string | null;
    type?: string | null;
    contactId?: number;
};

export type GetApiContactsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Contacts';
};

export type GetApiContactsResponses = {
    /**
     * OK
     */
    200: Array<Contact>;
};

export type GetApiContactsResponse = GetApiContactsResponses[keyof GetApiContactsResponses];

export type PostApiContactsData = {
    body?: Contact;
    path?: never;
    query?: never;
    url: '/api/Contacts';
};

export type PostApiContactsResponses = {
    /**
     * OK
     */
    200: Contact;
};

export type PostApiContactsResponse = PostApiContactsResponses[keyof PostApiContactsResponses];

export type DeleteApiContactsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Contacts/{id}';
};

export type DeleteApiContactsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiContactsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Contacts/{id}';
};

export type GetApiContactsByIdResponses = {
    /**
     * OK
     */
    200: ContactWithFullName;
};

export type GetApiContactsByIdResponse = GetApiContactsByIdResponses[keyof GetApiContactsByIdResponses];

export type PutApiContactsByIdData = {
    body?: Contact;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Contacts/{id}';
};

export type PutApiContactsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};
