// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiContactsByIdData, DeleteApiContactsByIdResponses, GetApiContactsBirthdaysData, GetApiContactsBirthdaysResponses, GetApiContactsByIdData, GetApiContactsByIdResponses, GetApiContactsData, GetApiContactsFavoritesData, GetApiContactsFavoritesResponses, GetApiContactsResponses, PatchApiContactsByIdFavoriteData, PatchApiContactsByIdFavoriteResponses, PostApiAuthLoginData, PostApiAuthLoginResponses, PostApiAuthRegisterData, PostApiAuthRegisterResponses, PostApiContactsData, PostApiContactsResponses, PutApiContactsByIdData, PutApiContactsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const postApiAuthRegister = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthRegisterData, ThrowOnError>): RequestResult<PostApiAuthRegisterResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostApiAuthRegisterResponses, unknown, ThrowOnError>({
    url: '/api/Auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthLoginData, ThrowOnError>): RequestResult<PostApiAuthLoginResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostApiAuthLoginResponses, unknown, ThrowOnError>({
    url: '/api/Auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getApiContacts = <ThrowOnError extends boolean = false>(options?: Options<GetApiContactsData, ThrowOnError>): RequestResult<GetApiContactsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiContactsResponses, unknown, ThrowOnError>({ url: '/api/Contacts', ...options });

export const postApiContacts = <ThrowOnError extends boolean = false>(options?: Options<PostApiContactsData, ThrowOnError>): RequestResult<PostApiContactsResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostApiContactsResponses, unknown, ThrowOnError>({
    url: '/api/Contacts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiContactsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiContactsByIdData, ThrowOnError>): RequestResult<DeleteApiContactsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteApiContactsByIdResponses, unknown, ThrowOnError>({ url: '/api/Contacts/{id}', ...options });

export const getApiContactsById = <ThrowOnError extends boolean = false>(options: Options<GetApiContactsByIdData, ThrowOnError>): RequestResult<GetApiContactsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetApiContactsByIdResponses, unknown, ThrowOnError>({ url: '/api/Contacts/{id}', ...options });

export const putApiContactsById = <ThrowOnError extends boolean = false>(options: Options<PutApiContactsByIdData, ThrowOnError>): RequestResult<PutApiContactsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).put<PutApiContactsByIdResponses, unknown, ThrowOnError>({
    url: '/api/Contacts/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiContactsBirthdays = <ThrowOnError extends boolean = false>(options?: Options<GetApiContactsBirthdaysData, ThrowOnError>): RequestResult<GetApiContactsBirthdaysResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiContactsBirthdaysResponses, unknown, ThrowOnError>({ url: '/api/Contacts/birthdays', ...options });

export const getApiContactsFavorites = <ThrowOnError extends boolean = false>(options?: Options<GetApiContactsFavoritesData, ThrowOnError>): RequestResult<GetApiContactsFavoritesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiContactsFavoritesResponses, unknown, ThrowOnError>({ url: '/api/Contacts/favorites', ...options });

export const patchApiContactsByIdFavorite = <ThrowOnError extends boolean = false>(options: Options<PatchApiContactsByIdFavoriteData, ThrowOnError>): RequestResult<PatchApiContactsByIdFavoriteResponses, unknown, ThrowOnError> => (options.client ?? client).patch<PatchApiContactsByIdFavoriteResponses, unknown, ThrowOnError>({
    url: '/api/Contacts/{id}/favorite',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
